'use client'
import { Canvas, useFrame } from '@react-three/fiber'
import { OrbitControls, Html, Line } from '@react-three/drei'
import { useRef } from 'react'
import * as THREE from 'three'
import { adjacentParcels, demoParcel, surveyPoints, utilitySegments } from '@/lib/spatial-data'

type UnitType = typeof demoParcel.building.floors[number]['units'][number]
type SceneProps = { floor?: number; underground?: boolean; verticalStack?: boolean; onSelectUnit?: (unit: UnitType) => void }
function Unit({x,z,y,unit,selected,onSelect}:{x:number;z:number;y:number;unit:UnitType;selected:boolean;onSelect:()=>void}){return <group position={[x,y,z]} onClick={e=>{e.stopPropagation();onSelect()}} onPointerOver={e=>{e.stopPropagation();document.body.style.cursor='pointer'}} onPointerOut={()=>{document.body.style.cursor='default'}}><mesh><boxGeometry args={[5.5,2.7,4.2]}/><meshStandardMaterial color={selected?'#68d3df':'#79a9b8'} transparent opacity={selected?.95:.64}/></mesh><mesh position={[0,1.38,0]}><boxGeometry args={[5.7,.08,4.4]}/><meshStandardMaterial color={selected?'#e9bb68':'#b7d0d7'}/></mesh>{selected&&<Html center distanceFactor={14}><div className="scene-label">{unit.verticalTag} · {unit.area} m²</div></Html>}</group>}
function MainBuilding({floor,verticalStack,underground,onSelectUnit}:{floor:number;verticalStack:boolean;underground:boolean;onSelectUnit?:SceneProps['onSelectUnit']}){const floors=demoParcel.building.floors;const fallback=floors[0].units[0];return <group>{floors.map((f,fi)=>f.units.map((u,i)=><Unit key={u.id} unit={u} x={i%2===0?-3:3} z={i<2?-2.3:2.3} y={fi*3.1+1.55+(verticalStack?fi*.9:0)} selected={u.verticalTag==='A03'||u.floor===floor} onSelect={()=>onSelectUnit?.(u)}/>))}<mesh position={[0,-1.1,0]} onClick={e=>{e.stopPropagation();onSelectUnit?.(fallback)}}><boxGeometry args={[12,2.1,10]}/><meshStandardMaterial color="#8ca3ac" transparent opacity={underground?.2:.35}/></mesh>{underground&&<><mesh position={[0,-3.2,0]} onClick={e=>{e.stopPropagation();onSelectUnit?.(fallback)}}><boxGeometry args={[12,2,10]}/><meshStandardMaterial color="#647f8b" transparent opacity={.75}/></mesh><mesh position={[0,-5.5,0]} onClick={e=>{e.stopPropagation();onSelectUnit?.(fallback)}}><boxGeometry args={[11,2,9]}/><meshStandardMaterial color="#526b78" transparent opacity={.72}/></mesh></>}<mesh position={[0,verticalStack?22:17,0]} onClick={e=>{e.stopPropagation();onSelectUnit?.(floors.at(-1)?.units[0]||fallback)}}><boxGeometry args={[13,1,11]}/><meshStandardMaterial color="#365367"/></mesh></group>}
function City({underground,onSelectUnit}:{underground:boolean;onSelectUnit?:SceneProps['onSelectUnit']}){return <group>{adjacentParcels().map((p,i)=><mesh key={i} position={[p.x,-.2,p.z]} rotation={[-Math.PI/2,0,0]} onClick={e=>{e.stopPropagation();onSelectUnit?.(demoParcel.building.floors[0].units[0])}}><planeGeometry args={[6,7]}/><meshStandardMaterial color={i%2?'#d2dfe2':'#c3d6d8'} transparent opacity={underground?.22:1}/></mesh>)}<mesh rotation={[-Math.PI/2,0,0]} position={[0,-.12,-18]}><planeGeometry args={[42,5]}/><meshStandardMaterial color="#87979b" transparent opacity={underground?.3:1}/></mesh><mesh rotation={[-Math.PI/2,0,0]} position={[-19,-.11,0]}><planeGeometry args={[5,42]}/><meshStandardMaterial color="#87979b" transparent opacity={underground?.3:1}/></mesh>{utilitySegments().map(i=><Line key={i} points={[[-14,-2.4+i*.18,0],[14,-2.4+i*.18,0]]} color="#c58a32" lineWidth={2}/>)}</group>}
function Survey({onSelectUnit}:{onSelectUnit?:SceneProps['onSelectUnit']}){return <group>{surveyPoints().map((p,i)=><mesh key={i} position={[p.x,.16,p.z]} onClick={e=>{e.stopPropagation();onSelectUnit?.(demoParcel.building.floors[0].units[0])}}><sphereGeometry args={[.14,12,12]}/><meshStandardMaterial color="#b5524e"/></mesh>)}</group>}
function SceneContent({floor,underground,verticalStack,onSelectUnit}:{floor:number;underground:boolean;verticalStack:boolean;onSelectUnit?:SceneProps['onSelectUnit']}){const ref=useRef<THREE.Group>(null);useFrame((_,d)=>{if(ref.current)ref.current.rotation.y+=d*.012});return <group ref={ref}><City underground={underground} onSelectUnit={onSelectUnit}/><MainBuilding floor={floor} underground={underground} verticalStack={verticalStack} onSelectUnit={onSelectUnit}/><Survey onSelectUnit={onSelectUnit}/><gridHelper args={[60,30,'#9db3b8','#c7d6d8']} position={[0,underground?-2.1:0,0]}/></group>}
export function SpatialScene({floor=3,underground=false,verticalStack=false,onSelectUnit}:SceneProps){return <div className="scene-wrap"><Canvas camera={{position:[27,22,28],fov:35}} shadows><color attach="background" args={['#dce7e8']}/><ambientLight intensity={2}/><directionalLight position={[10,30,12]} intensity={3}/><SceneContent floor={floor} underground={underground} verticalStack={verticalStack} onSelectUnit={onSelectUnit}/><OrbitControls makeDefault enableDamping dampingFactor={.08}/></Canvas><div className="scene-scale">N ↑ &nbsp; 1 : 2,500 &nbsp; METRIC</div></div>}
